### ISSUE TITLE
Segmentation fault on really old map files

### ISSUE THREAD

**Issue by Tarliton** [tibiamaps/tibia-maps-script#14]
I tried to generate PNG files from my old personal `.map` files and it crashes.

I believe it should acknowledge that the files are wrong and then exit the program gracefully.

You can download a small sample that crashes for testing here: [`Automapcrash.zip`](https://github.com/tibiamaps/tibia-maps-script/files/209664/Automapcrash.zip)

Thank you.

**Comment by mathiasbynens** [comment]
I can confirm the issue. Current output:

``` sh
$ tibia-maps --from-maps=Automap
`--output-dir` path not specified. Using the default, i.e. `data`.
/tmp/tibia-maps-cli-issue-14/data/bounds.json created successfully.
Rendering floor 03…
/tmp/tibia-maps-cli-issue-14/data/floor-03-map.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-03-path.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-03-markers.json created successfully.
Rendering floor 04…
/tmp/tibia-maps-cli-issue-14/data/floor-04-map.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-04-path.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-04-markers.json created successfully.
Rendering floor 05…
/tmp/tibia-maps-cli-issue-14/data/floor-05-map.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-05-path.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-05-markers.json created successfully.
Rendering floor 06…
/tmp/tibia-maps-cli-issue-14/data/floor-06-map.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-06-path.png created successfully.
/tmp/tibia-maps-cli-issue-14/data/floor-06-markers.json created successfully.
Rendering floor 07…
Segmentation fault: 11
```

The segfault occurs in node-canvas: https://github.com/Automattic/node-canvas/issues/749

**Comment by mathiasbynens** [comment]
Only the map files for floor 07 suffice to reproduce the issue:

``` sh
$ rm -- Automap/!(*07.map)

$ ls Automap
12412307.map 12412507.map 12412607.map 12412707.map

$ tibia-maps --from-maps=Automap
`--output-dir` path not specified. Using the default, i.e. `data`.
/tmp/tibia-maps-cli-issue-14/data/bounds.json created successfully.
Rendering floor 07…
Segmentation fault: 11
```

Updating `src/colors.js` with the full color list in https://github.com/tibiamaps/tibia-maps-script/issues/1#issuecomment-120704522 avoids the segfault.

**Comment by mathiasbynens** [comment]
Updating `src/colors.js` with the full color list in https://github.com/tibiamaps/tibia-maps-script/issues/1#issuecomment-120704522 avoids the segfault.

**Comment by mathiasbynens** [comment]
`tibia-maps` v2.6.2 now throws a proper exception in this case.

In case you want to convert your old maps anyway, just add the following entries to `byByte` in `node_modules/tibia-maps-script/src/colors.js`:

```
0x28: { r: 51, g: 0, b: 204 }, // dark blue (old water color)
0x1E: { r: 0, g: 255, b: 0 }, // green
```

**Comment by Tarliton** [comment]
Thanks!
