### ISSUE TITLE
Unknown color ID while trying to convert from maps on Linux

### ISSUE THREAD

**Issue by diegoamc** [tibiamaps/tibia-maps-script#19]
Hi,

I've been trying to convert my `*.map` files to `*.png`, but I'm getting the error `Unknown color ID`. Here's the full log:

```bash
tibia-maps --from-maps=./Automap --output-dir=./data

/data/bounds.json created successfully.
Rendering floor 00…

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: Unknown color ID: 40
    at Console.assert (console.js:95:23)
    at renderMap (/usr/lib/node_modules/tibia-maps/src/from-maps.js:74:12)
    at /usr/lib/node_modules/tibia-maps/src/from-maps.js:196:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:438:3)
```

Do you know how can I fix it? 

Thanks!

**Comment by mathiasbynens** [comment]
You could edit `/usr/lib/node_modules/tibia-maps/src/colors.js` as described here: https://github.com/tibiamaps/tibia-maps-script/issues/1#issuecomment-120704522 This way, all colors (not just the colors currently in use on official servers) are supported.

**Comment by diegoamc** [comment]
Thanks, that worked out nicely.
